name: Publish to gh-pages
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build and publish
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
      with:
        github_access_token: ${{ secrets.TOKEN }} # see the Configuration section for how you can create secrets
        build_configuration: production # The build environment for the app. please look configurations in your angular.json
        base_href: https://marnec.github.io/three-blog   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
        deploy_branch: main 
        # angular_dist_build_folder: ./dist/three-blog 

permissions:
  contents: write # Allow write permission to GITHUB_TOKEN to commit to deploy branch.